services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - spark-master
      - minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    networks:
      - my_network

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      - my_network  # Servisi aynı ağda tanımlıyoruz

  minio:
    image: quay.io/minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - my_network  # Servisi aynı ağda tanımlıyoruz

volumes:
  minio_data:

networks:
  my_network:   # Aynı ağda tüm servislerin çalışabilmesi için tanımlıyoruz
    driver: bridge