services:

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master2
    environment:
      - SPARK_MODE=master
    ports:
      - "8085:8080"
    networks:
      - my_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio2
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - my_network

volumes:
  minio_data:

networks:
  my_network:
    driver: bridge
